### ISSUE TITLE
Research Youtube Shorts

### ISSUE THREAD

**Issue by twentysixmoons** [arachne-threat-intel/community#7]
Identify aspects of using youtube shorts and short form video on youtube and LinkedIn where we currently have a social audience: 

- https://support.google.com/youtube/answer/10059070?hl=en
- https://buffer.com/resources/grow-youtube-shorts/
- https://www.linkedin.com/pulse/what-short-video-feature-linkedin-anthony-sutton-nns7c/
- https://buffer.com/resources/youtube-shorts-algorithm/

**Comment by twentysixmoons** [comment]
I researched here and determined that we would hold off on creating shorts specifically and focus more on posting our recordings after the call/webinar on YouTube and slowly growing our audience while getting used to the Youtube platform. 

When we increase capacity it's best to do shorts that are 30 second - 1-minute clips. 

It may be best to start creating shorts to answer questions about cyber security, cyber threat intelligence, and our specific project. Creating videos that answer reoccurring questions or are short explainer videos may be helpful and aligned when we are ready.

**Comment by jecarr** [comment]
Hey @twentysixmoons - thanks for researching into this!

When I raised the idea of Shorts, I envisioned it as posting it at the same time as a full-length video and it being of the same content.

e.g. The Short at the end of this comment has a link to a longer YouTube video

So an Arachne example could be a 1 hour webinar we had:
- Save as a new video roughly 30s of a highlight of that webinar > was there a joke that got everyone laughing? Did someone say something profound about cybersec?
- Caption can be like watch our full video of this webinar (or something more exciting)
- And link to the fully-uploaded webinar in the Short (see example at bottom of comment)

Benefits:
- "In general, Shorts attract more views and likes per view than regular videos..." [[link](https://research.google/pubs/shorts-vs-regular-videos-on-youtube-a-comparative-analysis-of-user-engagement-and-content-creation-trends/)]
  - Same link says "However, Shorts do not outperform regular videos in the education and political categories as much as they do in other categories" so I wouldn't stress if you do want to park the idea of Shorts for now.
- It's like posting it twice and treating it like an ad for the fuller video
- We'd already have the content so wouldn't need to worry about extra effort in creating Shorts (except for cropping existing videos)

I had a quick look at the links you shared but do point out if what I'm suggesting may deter users rather than the intention of getting them interested in our content?

Finally,

> It may be best to start creating shorts to answer questions about cyber security, cyber threat intelligence, and our specific project. Creating videos that answer reoccurring questions or are short explainer videos may be helpful and aligned when we are ready.

Yup, I agree! Sounds good! When we are ready to create new content for Shorts specifically, this sounds great.

---

The example (sorry the image displays massively!):

https://youtube.com/shorts/W_Zy1c5-uTg

![IMG_3211](https://github.com/user-attachments/assets/27a9e558-33f5-4435-b764-462f533a27e9)
